name: "Format Issue ID"
description: "Appends formatted ID to GitHub issue titles"
author: "xkeshav"

branding:
  icon: "activity"
  color: "gray-dark"

inputs:
  prefix:
    description: "Prefix for the identifier (e.g., TZF)"
    required: true
    default: "PRO"
    type: string

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        chmod +x "${{ github.action_path }}/format.sh"
        "${{ github.action_path }}/format.sh" \
          "${{ github.event.issue.number }}" \
          "${{ github.event.issue.title }}" \
          "${{ inputs.prefix }}"
